## Data Handling Basics Part 1: NumPy (Numerical Computing in Python)

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [3]:
# Python Lists
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [4]:
# Numpy Arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


NumPy performs element-wise operations.

In [5]:
# Basic Array Operations 

arr = np.array([1,2,3,4])

print(arr+10)
print(arr*2)

[11 12 13 14]
[2 4 6 8]


In [6]:
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

2.5
10
4
1


In [10]:
print('Zeros:',np.zeros(5))
print('Ones:',np.ones(4))
print('Range:', np.arange(1,10))

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1.]
Range: [1 2 3 4 5 6 7 8 9]


In [11]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# Create NumPy array of numbers 1-10
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Add 5 to every element
print(arr + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [14]:
# Find mean and sum of array
print(f"Mean: {np.mean(arr)}")
print(f"Sum: {np.sum(arr)}")

Mean: 5.5
Sum: 55


In [ ]:
# One dimensional array
myarray = np.array([3,4,5])

print(myarray.shape)

(3,)


In [17]:
# Create a 3 by 3 matrix
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]
])

print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
print(f"Max: {np.max(arr)}")
print(f"Max array3: {np.max(arr3)}")

Max: 10
Max array3: 9


## Data Handling Part 2: Pandas

In [25]:
import pandas as pd

**What is a Series**  

A Series is a one-dimensional labeled array.

In [26]:
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64


**What is a DataFrame**  

A DataFrame is a table (like Excel).

In [27]:
data = {
    'Name': ['Amit', 'Deepak', 'Ravi'],
    'Marks': [78,85,90]
}

df = pd.DataFrame(data)
print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
2    Ravi     90


In [28]:
# Reading CSV Files

df = pd.read_csv('students.csv')
print(df)

     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92


In [29]:
# Basic Data Exploration
print(df.head()) 
print(df.tail())
print(df.shape)
print(df.columns)

     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92
     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92
(5, 2)
Index(['Name', 'Marks'], dtype='object')


In [30]:
# Basic Statistics
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

75.6
92
35


In [31]:
# Sales Data
data = {
    'Product': ['A','B','C'],
    'Sales':[100,150,200]
}

df = pd.DataFrame(data)
print("Total Sales:", df['Sales'].sum())

Total Sales: 450


In [32]:
# Create DataFrame of students with name and marks
data = {
    'Name': ['Amit', 'Deepak', 'Ravi', 'Neha'],
    'Marks': [78,85,90,82]
}
df = pd.DataFrame(data)
print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
2    Ravi     90
3    Neha     82


In [33]:
# Print first 3 row using head()
print(df.head(3))

     Name  Marks
0    Amit     78
1  Deepak     85
2    Ravi     90


In [34]:
# Find average marks
print('Average Marks:', df['Marks'].mean())

Average Marks: 83.75


In [35]:
# Find highest marks
print('Highest Marks:', df['Marks'].max())

Highest Marks: 90


In [36]:
# Select only Name column
df['Name']

0      Amit
1    Deepak
2      Ravi
3      Neha
Name: Name, dtype: object

## Data Handling Basics Part 3: Data Cleaning with Pandas  

Common problems:  
- Missing values
- Duplicate rows
- Wrong data types
- Extra spaces / inconsistent values