## Data Handling Basics Part 1: NumPy (Numerical Computing in Python)

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [3]:
# Python Lists
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [4]:
# Numpy Arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


NumPy performs element-wise operations.

In [5]:
# Basic Array Operations 

arr = np.array([1,2,3,4])

print(arr+10)
print(arr*2)

[11 12 13 14]
[2 4 6 8]


In [6]:
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

2.5
10
4
1


In [10]:
print('Zeros:',np.zeros(5))
print('Ones:',np.ones(4))
print('Range:', np.arange(1,10))

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1.]
Range: [1 2 3 4 5 6 7 8 9]


In [11]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# Create NumPy array of numbers 1-10
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Add 5 to every element
print(arr + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [14]:
# Find mean and sum of array
print(f"Mean: {np.mean(arr)}")
print(f"Sum: {np.sum(arr)}")

Mean: 5.5
Sum: 55


In [ ]:
# One dimensional array
myarray = np.array([3,4,5])

print(myarray.shape)

(3,)


In [17]:
# Create a 3 by 3 matrix
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]
])

print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
print(f"Max: {np.max(arr)}")
print(f"Max array3: {np.max(arr3)}")

Max: 10
Max array3: 9
